// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trips.proto2

package com.jerolba.parquet.protocol.model;

public final class Trips {
  private Trips() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jerolba_parquet_protocol_model_Trip_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jerolba_parquet_protocol_model_Trip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014trips.proto2\022\"com.jerolba.parquet.prot" +
      "ocol.model\"e\n\004Trip\022\034\n\024dispatching_base_n" +
      "um\030\001 \002(\t\022\030\n\020request_datetime\030\002 \002(\003\022\022\n\ntr" +
      "ip_miles\030\003 \002(\001\022\021\n\ttrip_time\030\004 \002(\003B-\n\"com" +
      ".jerolba.parquet.protocol.modelB\005TripsP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jerolba_parquet_protocol_model_Trip_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jerolba_parquet_protocol_model_Trip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jerolba_parquet_protocol_model_Trip_descriptor,
        new java.lang.String[] { "DispatchingBaseNum", "RequestDatetime", "TripMiles", "TripTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
