// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trips.proto2

package com.jerolba.parquet.protocol.model;

public interface TripOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jerolba.parquet.protocol.model.Trip)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string dispatching_base_num = 1;</code>
   */
  boolean hasDispatchingBaseNum();
  /**
   * <code>required string dispatching_base_num = 1;</code>
   */
  java.lang.String getDispatchingBaseNum();
  /**
   * <code>required string dispatching_base_num = 1;</code>
   */
  com.google.protobuf.ByteString
      getDispatchingBaseNumBytes();

  /**
   * <code>required int64 request_datetime = 2;</code>
   */
  boolean hasRequestDatetime();
  /**
   * <code>required int64 request_datetime = 2;</code>
   */
  long getRequestDatetime();

  /**
   * <code>required double trip_miles = 3;</code>
   */
  boolean hasTripMiles();
  /**
   * <code>required double trip_miles = 3;</code>
   */
  double getTripMiles();

  /**
   * <code>required int64 trip_time = 4;</code>
   */
  boolean hasTripTime();
  /**
   * <code>required int64 trip_time = 4;</code>
   */
  long getTripTime();
}
