// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trips.proto2

package com.jerolba.parquet.protocol.model;

/**
 * Protobuf type {@code com.jerolba.parquet.protocol.model.Trip}
 */
public  final class Trip extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.jerolba.parquet.protocol.model.Trip)
    TripOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Trip.newBuilder() to construct.
  private Trip(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Trip() {
    dispatchingBaseNum_ = "";
    requestDatetime_ = 0L;
    tripMiles_ = 0D;
    tripTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Trip(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            dispatchingBaseNum_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            requestDatetime_ = input.readInt64();
            break;
          }
          case 25: {
            bitField0_ |= 0x00000004;
            tripMiles_ = input.readDouble();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            tripTime_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jerolba.parquet.protocol.model.Trips.internal_static_com_jerolba_parquet_protocol_model_Trip_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jerolba.parquet.protocol.model.Trips.internal_static_com_jerolba_parquet_protocol_model_Trip_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jerolba.parquet.protocol.model.Trip.class, com.jerolba.parquet.protocol.model.Trip.Builder.class);
  }

  private int bitField0_;
  public static final int DISPATCHING_BASE_NUM_FIELD_NUMBER = 1;
  private volatile java.lang.Object dispatchingBaseNum_;
  /**
   * <code>required string dispatching_base_num = 1;</code>
   */
  public boolean hasDispatchingBaseNum() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string dispatching_base_num = 1;</code>
   */
  public java.lang.String getDispatchingBaseNum() {
    java.lang.Object ref = dispatchingBaseNum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        dispatchingBaseNum_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string dispatching_base_num = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDispatchingBaseNumBytes() {
    java.lang.Object ref = dispatchingBaseNum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dispatchingBaseNum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUEST_DATETIME_FIELD_NUMBER = 2;
  private long requestDatetime_;
  /**
   * <code>required int64 request_datetime = 2;</code>
   */
  public boolean hasRequestDatetime() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int64 request_datetime = 2;</code>
   */
  public long getRequestDatetime() {
    return requestDatetime_;
  }

  public static final int TRIP_MILES_FIELD_NUMBER = 3;
  private double tripMiles_;
  /**
   * <code>required double trip_miles = 3;</code>
   */
  public boolean hasTripMiles() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required double trip_miles = 3;</code>
   */
  public double getTripMiles() {
    return tripMiles_;
  }

  public static final int TRIP_TIME_FIELD_NUMBER = 4;
  private long tripTime_;
  /**
   * <code>required int64 trip_time = 4;</code>
   */
  public boolean hasTripTime() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required int64 trip_time = 4;</code>
   */
  public long getTripTime() {
    return tripTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasDispatchingBaseNum()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRequestDatetime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTripMiles()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTripTime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dispatchingBaseNum_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, requestDatetime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeDouble(3, tripMiles_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt64(4, tripTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dispatchingBaseNum_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, requestDatetime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, tripMiles_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, tripTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jerolba.parquet.protocol.model.Trip)) {
      return super.equals(obj);
    }
    com.jerolba.parquet.protocol.model.Trip other = (com.jerolba.parquet.protocol.model.Trip) obj;

    boolean result = true;
    result = result && (hasDispatchingBaseNum() == other.hasDispatchingBaseNum());
    if (hasDispatchingBaseNum()) {
      result = result && getDispatchingBaseNum()
          .equals(other.getDispatchingBaseNum());
    }
    result = result && (hasRequestDatetime() == other.hasRequestDatetime());
    if (hasRequestDatetime()) {
      result = result && (getRequestDatetime()
          == other.getRequestDatetime());
    }
    result = result && (hasTripMiles() == other.hasTripMiles());
    if (hasTripMiles()) {
      result = result && (
          java.lang.Double.doubleToLongBits(getTripMiles())
          == java.lang.Double.doubleToLongBits(
              other.getTripMiles()));
    }
    result = result && (hasTripTime() == other.hasTripTime());
    if (hasTripTime()) {
      result = result && (getTripTime()
          == other.getTripTime());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDispatchingBaseNum()) {
      hash = (37 * hash) + DISPATCHING_BASE_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getDispatchingBaseNum().hashCode();
    }
    if (hasRequestDatetime()) {
      hash = (37 * hash) + REQUEST_DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestDatetime());
    }
    if (hasTripMiles()) {
      hash = (37 * hash) + TRIP_MILES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTripMiles()));
    }
    if (hasTripTime()) {
      hash = (37 * hash) + TRIP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTripTime());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jerolba.parquet.protocol.model.Trip parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jerolba.parquet.protocol.model.Trip prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.jerolba.parquet.protocol.model.Trip}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.jerolba.parquet.protocol.model.Trip)
      com.jerolba.parquet.protocol.model.TripOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jerolba.parquet.protocol.model.Trips.internal_static_com_jerolba_parquet_protocol_model_Trip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jerolba.parquet.protocol.model.Trips.internal_static_com_jerolba_parquet_protocol_model_Trip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jerolba.parquet.protocol.model.Trip.class, com.jerolba.parquet.protocol.model.Trip.Builder.class);
    }

    // Construct using com.jerolba.parquet.protocol.model.Trip.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dispatchingBaseNum_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      requestDatetime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      tripMiles_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000004);
      tripTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jerolba.parquet.protocol.model.Trips.internal_static_com_jerolba_parquet_protocol_model_Trip_descriptor;
    }

    public com.jerolba.parquet.protocol.model.Trip getDefaultInstanceForType() {
      return com.jerolba.parquet.protocol.model.Trip.getDefaultInstance();
    }

    public com.jerolba.parquet.protocol.model.Trip build() {
      com.jerolba.parquet.protocol.model.Trip result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jerolba.parquet.protocol.model.Trip buildPartial() {
      com.jerolba.parquet.protocol.model.Trip result = new com.jerolba.parquet.protocol.model.Trip(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.dispatchingBaseNum_ = dispatchingBaseNum_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.requestDatetime_ = requestDatetime_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.tripMiles_ = tripMiles_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.tripTime_ = tripTime_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jerolba.parquet.protocol.model.Trip) {
        return mergeFrom((com.jerolba.parquet.protocol.model.Trip)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jerolba.parquet.protocol.model.Trip other) {
      if (other == com.jerolba.parquet.protocol.model.Trip.getDefaultInstance()) return this;
      if (other.hasDispatchingBaseNum()) {
        bitField0_ |= 0x00000001;
        dispatchingBaseNum_ = other.dispatchingBaseNum_;
        onChanged();
      }
      if (other.hasRequestDatetime()) {
        setRequestDatetime(other.getRequestDatetime());
      }
      if (other.hasTripMiles()) {
        setTripMiles(other.getTripMiles());
      }
      if (other.hasTripTime()) {
        setTripTime(other.getTripTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasDispatchingBaseNum()) {
        return false;
      }
      if (!hasRequestDatetime()) {
        return false;
      }
      if (!hasTripMiles()) {
        return false;
      }
      if (!hasTripTime()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jerolba.parquet.protocol.model.Trip parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jerolba.parquet.protocol.model.Trip) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object dispatchingBaseNum_ = "";
    /**
     * <code>required string dispatching_base_num = 1;</code>
     */
    public boolean hasDispatchingBaseNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string dispatching_base_num = 1;</code>
     */
    public java.lang.String getDispatchingBaseNum() {
      java.lang.Object ref = dispatchingBaseNum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dispatchingBaseNum_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string dispatching_base_num = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDispatchingBaseNumBytes() {
      java.lang.Object ref = dispatchingBaseNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dispatchingBaseNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string dispatching_base_num = 1;</code>
     */
    public Builder setDispatchingBaseNum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      dispatchingBaseNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string dispatching_base_num = 1;</code>
     */
    public Builder clearDispatchingBaseNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      dispatchingBaseNum_ = getDefaultInstance().getDispatchingBaseNum();
      onChanged();
      return this;
    }
    /**
     * <code>required string dispatching_base_num = 1;</code>
     */
    public Builder setDispatchingBaseNumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      dispatchingBaseNum_ = value;
      onChanged();
      return this;
    }

    private long requestDatetime_ ;
    /**
     * <code>required int64 request_datetime = 2;</code>
     */
    public boolean hasRequestDatetime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 request_datetime = 2;</code>
     */
    public long getRequestDatetime() {
      return requestDatetime_;
    }
    /**
     * <code>required int64 request_datetime = 2;</code>
     */
    public Builder setRequestDatetime(long value) {
      bitField0_ |= 0x00000002;
      requestDatetime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 request_datetime = 2;</code>
     */
    public Builder clearRequestDatetime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestDatetime_ = 0L;
      onChanged();
      return this;
    }

    private double tripMiles_ ;
    /**
     * <code>required double trip_miles = 3;</code>
     */
    public boolean hasTripMiles() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double trip_miles = 3;</code>
     */
    public double getTripMiles() {
      return tripMiles_;
    }
    /**
     * <code>required double trip_miles = 3;</code>
     */
    public Builder setTripMiles(double value) {
      bitField0_ |= 0x00000004;
      tripMiles_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double trip_miles = 3;</code>
     */
    public Builder clearTripMiles() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tripMiles_ = 0D;
      onChanged();
      return this;
    }

    private long tripTime_ ;
    /**
     * <code>required int64 trip_time = 4;</code>
     */
    public boolean hasTripTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 trip_time = 4;</code>
     */
    public long getTripTime() {
      return tripTime_;
    }
    /**
     * <code>required int64 trip_time = 4;</code>
     */
    public Builder setTripTime(long value) {
      bitField0_ |= 0x00000008;
      tripTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 trip_time = 4;</code>
     */
    public Builder clearTripTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tripTime_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.jerolba.parquet.protocol.model.Trip)
  }

  // @@protoc_insertion_point(class_scope:com.jerolba.parquet.protocol.model.Trip)
  private static final com.jerolba.parquet.protocol.model.Trip DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jerolba.parquet.protocol.model.Trip();
  }

  public static com.jerolba.parquet.protocol.model.Trip getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Trip>
      PARSER = new com.google.protobuf.AbstractParser<Trip>() {
    public Trip parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trip(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Trip> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Trip> getParserForType() {
    return PARSER;
  }

  public com.jerolba.parquet.protocol.model.Trip getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

